### ISSUE TITLE
Disable shortcut keys

### ISSUE THREAD

**Issue by marcospassos** [uber/react-digraph#10]
Is there any way to disable the default shortcut keys? Additionally, I could not find any way to add a node programmatically, is it possible?

**Comment by johnvf** [comment]
It should be possible (and ... I think, preferable) to at least expose the shortcut keys as props so that a user can tailor them to their needs (or null them out, if desired).

**Comment by johnvf** [comment]
In response to your second question - it should be easy to add a node programmatically. You can directly update the nodes and edges props that are passed into GraphView.js - you could also call whatever implementation of 'onCreateNode' you write from elsewhere in the code (see: https://github.com/uber/react-digraph/blob/master/src/examples/graph.js#L173)

EG, somewhere else, if 'graph.js' were a child component and you assigned a 'ref' to it, you could do this.graph.onCreateNode(x, y).

**Comment by ajbogh** [comment]
@marcospassos This is an interesting idea. Can you be more specific as to which keys you would like to ignore? We currently listen for Delete and Backspace, while the Shift key is used for creating nodes and edges.

I see it being useful to reassign keys as well as disabling them if desired.

If you would like to prevent any interaction with the graph you could set it to readOnly.

You could also override the class by using a React ref, then modifying the `handleWrapperKeydown` function:

```
this.graphView.handleWrapperKeydown = (d, i) => {
  // do nothing
}
```

**Comment by Malikx-Alee** [comment]
@ajbogh @thinkty  how can we modify handleWrapperKeydown using ref ? It would be great help if you could also provide an example.

**Comment by thinkty** [comment]
@Malikx-Alee The pull request (#252) related to this issue has been merged to master. I can't remember how it was done using ref but I think it will be better to use props instead as using refs is not the [*React way*](https://reactjs.org/docs/thinking-in-react.html).

However, I just started using React so I might be wrong.
