### ISSUE TITLE
Node selection problem on Firefox 64.0

### ISSUE THREAD

**Issue by pplonski** [uber/react-digraph#104]
**Describe the bug**
I'm running demo example. When I click on the node (in the area where is no text) then the node is selected. But when I click on node title the node is not selected. I observe this bug on Firefox 64.0 and Ubuntu 16.04. It is working as expected on Chrome 69. 

**To Reproduce**
1. Clone the repo and run demo example.
2. Click on any node (in the area with no text) the node is selected. 
3. Click on any node (in the area with text) the node is not selected. 

**Expected behavior**
The node should be selected no matter if we click on area with text or not.

**Desktop:**
 - OS: Ubuntu 16.04
 - Browser Firefox
 - Version 64.0

**Additional context**
The bug is not observed on Chrome 69.

**Comment by pplonski** [comment]
I found the fix. In the method `onSelectNode` there is missing check if `viewNode` is not null. If added then all works as expected.

**Comment by ianchanning** [comment]
@pplonski It's great that you've found a resolution, but I think this issue should remain open until a PR is submitted that fixes the bug

**Comment by adamsvystun** [comment]
Also, checking for null is actually not a solution. `null` should represent the click outside off any node or edge. It is used for deselection.
