### ISSUE TITLE
Annotate edges

### ISSUE THREAD

**Issue by GerwinBosch** [uber/react-digraph#12]
Hi, is there a way to have text added to edges?

**Comment by johnvf** [comment]
There isn't currently a way, but I would totally be open to adding it. If you need it immediately, feel free to add submit a PR. Otherwise, I'll add it to my roadmap.

**Comment by johnvf** [comment]
It is now be possible to modify/override the renderEdge method as a prop - it should be possible to attach additional attributes to edge objects and display them in your home-rolled renderEdge method.
