### ISSUE TITLE
Node creation rendering bug

### ISSUE THREAD

**Issue by alekseyl1992** [uber/react-digraph#13]
**Steps to reproduce:**
1. create a project based on example
2. Shift + Click somewhere

**Expected behaviour:**
New node created and rendered

**Actual behaviour:**
Nothing happens visually, until I drag something.

I figured out the way to fix it by myself, but it's seems to be inefficient:
https://github.com/uber/react-digraph/blob/master/src/components/graph-view.js#L884
calling `renderViews()` twice in a row fixes the problem.

I think better solution would imply either:
1. some kind of proper data update before render() is called
2. calling `renderViews()` on node creation callback (inside of `graph-view.js` of cource)

**Comment by johnvf** [comment]
Interesting - I'm surprised I missed this ... perhaps something changed with a dependency or this issue is somehow covered up in my wrapper for GraphView.

I'll look into this ASAP

**Comment by mac-s-g** [comment]
I'm getting the same issue - but it looks like the link for the fix is out of date.

any recommended fix?

**Comment by mac-s-g** [comment]
update:  I was able to avoid the double render issue by explicitly setting `state.selected` to an empty object when creating nodes and edges.

current example code:
```
onCreateNode = (x,y) => {
  ...
  // not re-rendering properly
  this.setState({graph: graph});
}
...
onCreateEdge = (sourceViewNode, targetViewNode) => {
  ...
  // not re-rendering properly
  this.setState({graph: graph});
}
```

revised example code:
```
onCreateNode = (x,y) => {
  ...
  // re-rendering properly
  this.setState({graph: graph, selected: {}});
}
...
onCreateEdge = (sourceViewNode, targetViewNode) => {
  ...
  // re-rendering properly
  this.setState({graph: graph, selected: {}});
}
```

this solution works for now, but it would be more intuitive to push `selected` handling down to lower layers when nodes or edges are created.
