### ISSUE TITLE
Add horizontal tree layout engine

### ISSUE THREAD

**Issue by wfriebel** [uber/react-digraph#135]
**Describe the solution you'd like**
I would like to add a horizontal tree layout engine.

**Describe alternatives you've considered**
I considered addressing issue #126 to add the ability to pass GraphView a custom layout-engine. For now, I will follow the current design and add a new layout engine to the project.

**Comment by ajbogh** [comment]
#136 has been merged and will be in the next release (v6.4.0 or greater).
