### ISSUE TITLE
Vote: Convert to Typescript

### ISSUE THREAD

**Issue by ajbogh** [uber/react-digraph#138]
**Is your feature request related to a problem? Please describe.**

Originally during the development phase of v5.0, this code was created in Typescript due to its huge popularity and Typescript's ease of development, including feature support such as being able to handle import loops (a necessity for a certain part of this project).

After the internal review, it was decided to switch to Flowtype since that's what Uber uses internally. We decided to make the project use the same type system that other Uber developers are already comfortable with. You may have noticed some types using the Typescript-style "ISomething" for interfaces. This style is going out of phase for Typescript now, but it was required when the development phase began. Other parts of the code still don't compile well with Flowtype since it's using Typescript types, this is partly due to better documentation on certain types, and partly due to a lack of breaking builds when Flowtype fails. We decided to enable Flow type checking in the editor without making the builds break because external developers may not know how to develop with Flow, so a less intrusive error in the editor would be easier to deal with.

Often Flow crashes in the editor (VSCode), either with a wrong version error or due to some type check that failed and crashed the server. When this happens the editor no longer highlights errors and files look like they are correct, making it impossible for the developer to fix errors without running `npm run flow` manually. Server crashes are bothersome and require developers to review Github issues in Flow to determine if the Flow team fixed the problem. This takes time out of a developer's day and pulls them away from useful feature development.

Since v5 development began, Typescript has become allowed as a new development language (partly due to a 34 page document put together by myself, the issue creator). We are allowed to use it for projects within Uber, however it is not an officially supported language in the company just yet. There are many developers that are working on Typescript projects and which are excited to use it in other areas.

**Describe the solution you'd like**

A Vote: 

A Note on the emoticons used for voting. I didn't want to skew the perspective of Flow or Typescript by using thumbs up or down, but the quick-pick reactions only allow a certain set of emoticons. Please don't let a thumbs up or down change your choice.

**Thumbs up** for Typescript if you would like to switch 👍 
**Thumbs down** to stay with Flow if you don't like this idea 👎  

**Describe alternatives you've considered**

Alternative 1: ignore all opinions and switch to Typescript by dictatorship rule
  - not desirable, this is not a single developer project 
  - makes Flow fans unhappy since they didn't get a voice

Alternative 2: stay with Flow and just fix errors
  - reduces the number of available developers since Flow is not a well known language
  - uses hacks to make the types work
  - requires many code changes to fix existing type problems (may be equivalent to switching)

**Comment by chiwoojo** [comment]
I'm very excited to see this project go to Typescript. It's a very powerful typing system compared with Flow.

**Comment by vicapow** [comment]
> Often Flow crashes in the editor (VSCode),

If this ever happens, please reach out to me 1:1 I'd very much like to debug anyone that might experience stability issues with Flow at Uber. [We have seen some stability issues with Flow + iCloud configurations. This seems to be related to a bug in watchman + iCloud](https://github.com/facebook/flow/issues/6825) triggering updates. Aside from that, we're not aware of any other crashing related incidents with VSCode + Flow. Sometimes there can be misconfigurations between vscode + flow. We don't see this as much with TypeScript because they don't implement the Language Server Protocol in tserver and they also preconfigure TS with VSCode as a built in extension. We could consider doing the same for Flow and that might help cut down on the editor configuration related issues.

**Comment by ajbogh** [comment]
I believe this vote shows a desire to switch to Typescript. Currently we're at 16 for Typescript vs 7 for Flow, so we will convert to Typescript.

An added benefit to this change may be the removal of Webpack and Babel, but we will be careful with this.

See #163 for the issue to convert to Typescript. PRs should reference #163.
