### ISSUE TITLE
GraphView doesn't fill the whole screen

### ISSUE THREAD

**Issue by jiujianxian** [uber/react-digraph#160]
Why does the graph editor does not fill the whole browser screen? Instead, it concentrates on the top 1/3 of the browser window? How does one change that? Thank you very much

**Comment by iChaosren** [comment]
Just make sure the div that's containing the graph is stretching to fill the screen:

flex: 1,
width: '100%',
height: '100%',
overflow: 'hidden',
position: 'relative' | 'absolute' // depending on how your project is setup

The graph itself does stretch to fill its container.

**Comment by ajbogh** [comment]
@jiujianxian I am going to close this assuming @iChaosren has answered your question. The graph will only fill in the space provided by its direct parent. If the parent element or div is not wide or high enough to fill the screen, then your graph won't be either.

**Comment by maifeeulasad** [comment]
@iChaosren just formatted the code a little :
```
.parent{
    flex: 1;
    width: 100%;
    height: 100%;
    overflow: hidden;
    position: absolute
}
```
