### ISSUE TITLE
Editable Node Elements

### ISSUE THREAD

**Issue by jtfell** [uber/react-digraph#170]
**Is your feature request related to a problem? Please describe.**

I would like to be able to render objects that have editable text fields inside the nodes. I have managed to to render a `foreignObject` element, containing an `input` element inside the node using the `renderNode` prop. This is working as expected.

The problem arises when I try to interact with this input field in the DOM, as clicking on it causes a re-render, consequently causing the fresh input field to not be focused.

**Describe the solution you'd like**

I would like some way to prevent click/input events on the node or elements inside it from causing re-renders. Ideally this would be controllable through a callback to decide if the element clicked on should cause a "prevented" click (that doesn't cause a re-render) or allow the event to propagate to the diagram and interact with the nodes as normal (eg. create an edge, move the node).

**Describe alternatives you've considered**

I've made significant changes to try to prevent this re-rendering (including commenting out almost all the click handlers) but I think I am misunderstanding the way you are using `ReactDOM.render` for each node. It seems that whenever a node is clicked on, there is a handler somewhere removing and re-creating the root element.

**Additional context**

This issue is blocking me on my project so I'm very keen to get it resolved. If anyone can point me in the right direction in terms of understanding what is happening, I'm happy to make the changes and contribute a PR. Please let me know if any clarifications will help :)

**Comment by iChaosren** [comment]
I have two quick fixes you can try:

- Implement the `onFocus`/`onClick` or something similar on the input to make it a fully managed component.

OR

- Try preventing the click event from propagating. i.e. `onClick={(e) => e.preventPropagation()}` or something similar. This will prevent any other related click events from firing.

**Comment by jtfell** [comment]
Thanks @iChaosren, the issue turned out to be related to this code:

https://github.com/uber/react-digraph/blob/master/src/components/node.js#L230
https://github.com/uber/react-digraph/blob/master/src/components/node.js#L208

I found a way to solve it for my use case, so I'll add a PR later today in case this feature is useful for others

**Comment by Bhagyashri1808** [comment]
@jtfell Please could you tell me what are the fixes worked for you. I also have the same issue. I am able to add input fields in nodes. The Problem is, for example, I have nodes 1,2, and 3, the input field present in the third node is editable rest of them are not editable. I tried all the above solutions. Please help me I am stuck in between.
