### ISSUE TITLE
index.d.ts out of date / out of sync

### ISSUE THREAD

**Issue by klintu** [uber/react-digraph#190]
Not sure if there are any other instances, but the IGraphViewProps defined in graph-view-props.js doesn't match the IGraphViewProps typing in index.d.ts

The specific case I noticed was that index.d.ts is missing the onBackgroundClick event.

**Comment by ajbogh** [comment]
Thank you for flagging that. Please feel free to help with a PR, or we will address it soon. Ultimately we will generate these types automatically or convert the project to Typescript, however our available time is limited. If you can help in any way, we would very much appreciate the support.

**Comment by ajbogh** [comment]
Thanks once again. I was able to set aside some time to complete this today. Please feel free to open other issues if you find something missing.
