### ISSUE TITLE
renderBackground usage

### ISSUE THREAD

**Issue by ovvioinfame233** [uber/react-digraph#194]
I'm having some issues changing the background of the SVG. When I change the background in my browser (Chome), it reflects the change. How is the renderBackgound used to change the SVG, in terms of formatting?

**Comment by iChaosren** [comment]
The `renderBackground` overrides the existing background rendered component.

Literally looks something like this:

```jsx
class Background extends React.Component {
   render() {
      if(this.props.renderBackground != null) {
         return renderBackground(this.props.gridSize)
      }

      return <rect {...someProps} />
   }
}
```

If you just want to change the background, your best bet is to use `backgroundFillId` in conjunction with `renderDefs` which renders any additional definitions.

ie.
```jsx
renderDefs={() => <SomeCustomSVG id="newBackground" />}
backgroundFillId="#newBackground"
```

**Comment by chandjenAC** [comment]
Hi, I tried doing this to change the background as you said. But I couldn't make it work. 

This is my code.

  renderDefs={() => (
            <svg
              width="800px"
              height="600px"
              viewBox="0 0 800 600"
              id="background"
            >
              <rect
                x="0"
                y="0"
                width="800px"
                height="600px"
                fill="black"
              ></rect>
            </svg>
          )}
          backgroundFillId="#background"

 I am not sure if I'm doing something wrong. I am currently working on a project and I have been trying to achieve this.
Please help!.  Thank you.

**Comment by chandjenAC** [comment]
Hi, I tried what you said. But I couldn't set the background. I'm not able to see what's wrong in the code.. I have been working on a project and this is one of the things that I'm supposed to achieve. This is the code that I used.
`  renderDefs={() => (
            <svg
              width="800px"
              height="600px"
              viewBox="0 0 800 600"
              id="background"
            >
              <rect
                x="0"
                y="0"
                width="800px"
                height="600px"
                fill="black"
              ></rect>
            </svg>
          )}
          backgroundFillId="#background"`

This was given as prop to GraphView. But didnt get result.
Could you please provide me a working example. Thank you!

**Comment by chandjenAC** [comment]
i got it.. used a function like this.. it worked..i just wanted to change the background color.

`  const renderBackground = (gridSize) => {
    return (
      <rect
        className="background"
        x={-(gridSize || 0) / 4}
        y={-(gridSize || 0) / 4}
        width={gridSize}
        height={gridSize}
        fill={"black"}
      />
    );
  };

I like this module... keep up the good work.. thank you !
`
