### ISSUE TITLE
muti bug (internet Explorer 11)

### ISSUE THREAD

**Issue by AhmadYoussef** [uber/react-digraph#197]
**Describe the bug**
I am trying to use the library on the internet explorer 11 but the graph is not reacting well on the browser : 
1. the first problem that when I move the Node to another position I am still getting the old edge and the new one until I refresh the page.
2. every time I interact with the graph I am getting several errors in the console 
 "SCRIPT438 Object doesn't support property or method "remove"
"SCRIPT5007: Unable to get property 'nextsibling' of undefined or null reference"
"SCRIPT5007: Unable to get property 'contains' of undefined or null reference"

"The library working perfectly on the other browsers "

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : internet explorer 11
 - Version :11

**Additional context**
I am not sure if I am doing something wrong here. it would be nice if you could guide me to the right path

**Comment by ajbogh** [comment]
I'm sorry but we don't support IE11. You will need to use this with a modern browser such as Edge, Chrome, Firefox, Safari, or any of the open source browsers that make up the prior browsers such as Chromium, or derivatives of those browsers such as Pale Moon.

I recommend using a utility like [browser-update.org](https://browser-update.org/) to notify users that they need an up-to-date browser.
