### ISSUE TITLE
initialBBox always required now

### ISSUE THREAD

**Issue by EynsherKiel** [uber/react-digraph#199]
Hello

Property 'initialBBox' is missing in type '{ ref: string; nodeKey: string; nodes: any; edges: any; selected: any; nodeTypes: { empty: { typeText: string; shapeId: string; shape: Element; }; custom: { typeText: string; shapeId: string; shape: Element; }; }; ... 9 more ...; onDeleteEdge: { ...; }; }' but required in type 'Readonly<IGraphViewProps>'.  TS2741

**Comment by ajbogh** [comment]
Sorry, this was a bug that a new PR has been opened to fix. Please see #198.

**Comment by EynsherKiel** [comment]
Thank you!)
