### ISSUE TITLE
Edges overlay node shape

### ISSUE THREAD

**Issue by beders** [uber/react-digraph#203]
**Describe the bug**
Edges between shapes are drawn over the edge shape i.e. the edges seem to go from text box to text box. Not the actual shape.

**To Reproduce**

All node shapes are:
```
<symbol viewBox="0 0 50 25"  id="action" key=0 width=150 height=150>
  <rect width=50 height=25 rx=1></rect></symbol>
```

Edge shape for emptyEdge same as in sample code in Readme.

**Expected behavior**
Edge should not overlap.

**Screenshots**
<img width="667" alt="image" src="https://user-images.githubusercontent.com/522318/75329121-67930280-587f-11ea-8587-077c44306a3d.png">

**Desktop (please complete the following information):**
 Chrome, MacOS

**Additional context**
I'm using ClojureScript's Reagent library.
Maybe I'm missing a configuration option?

Can post more sample code, but it's in ClojureScript ;)

Thanks for any pointers in the right direction.

**Comment by ajbogh** [comment]
The viewbox is set to "0 0 50 25" but the width and height are 150. You need these to be consistent with the size of the image, so either 150w and maybe 75h (given the rectangular shape), or both viewbox and width/height should be 50/25. The code does its best to figure out the width and height from the viewbox, but it will use the width and height at times. In this case the code is using the viewbox.

**Comment by beders** [comment]
That makes all sense in the world. Thank you!
