### ISSUE TITLE
Not working on mobile?

### ISSUE THREAD

**Issue by RSchneider94** [uber/react-digraph#210]
I have just tried to test the project I'm working on using this lib in BrowserStack and it seems not to be working on iOS and Android (Chrome/Safari/etc.). When I tried to click on some node and pull it does nothing, unfortunately. Is the library not mobile ready? That would be really sad to hear, really enjoying the lib.

**Comment by ajbogh** [comment]
I'm sorry to say that this project is primarily developed for desktop use. There is _some_ support for touch events through d3, but it's not well tested by the primary developers. If you would like to help add support for mobile devices, please feel free to support the project with PRs. Your issues are welcome as well.

**Comment by RSchneider94** [comment]
Hey @ajbogh I see, thanks! I could make it work removing:

`const mouseButtonDown = event.sourceEvent.buttons === 1;`

and

```javascript
if (!mouseButtonDown) {
      return;
    }
```

inside node.js handleMouseMove function.
