### ISSUE TITLE
Behaviour for node with key=0

### ISSUE THREAD

**Issue by maekawataiki** [uber/react-digraph#212]
**Describe the bug**
Edge is not created for the node which has `node[NODE_KEY]=0`
Additionally, you cannot drag that node.

**To Reproduce**
Steps to reproduce the behaviour:
1. With the sample graph in the tutorial on top-level README.md
2. Add node with id=0 and connect to another node

That means for example,
```
{
    "nodes": [
        {
            "id": 0,
            "title": "Node 0",
            "x": 0,
            "y": 0,
            "type": "empty"
        },
        {
            "id": 1,
            "title": "Node A",
            "x": 258.3976135253906,
            "y": 331.9783248901367,
            "type": "empty"
        },
        {
            "id": 2,
            "title": "Node B",
            "x": 593.9393920898438,
            "y": 260.6060791015625,
            "type": "empty"
        },
        {
            "id": 3,
            "title": "Node C",
            "x": 237.5757598876953,
            "y": 61.81818389892578,
            "type": "custom"
        },
        {
            "id": 4,
            "title": "Node C",
            "x": 600.5757598876953,
            "y": 600.81818389892578,
            "type": "custom"
        }
    ],
    "edges": [
        {
            "source": 1,
            "target": 2,
            "type": "emptyEdge"
        },
        {
            "source": 2,
            "target": 4,
            "type": "emptyEdge"
        },
        {
            "source": 0,
            "target": 4,
            "type": "emptyEdge"
        }
    ]
}
```

**Expected behavior**
`Node with id=0` should be connected to `Node with id=4`
`Node with id=0` should be draggable.

**Screenshots**
<img width="614" alt="Screen Shot 2020-04-26 at 5 59 02 PM" src="https://user-images.githubusercontent.com/26317009/80320998-d17c4980-87e7-11ea-9904-beec7e62e10f.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 81.0.4044.122 (Official Build) (64-bit)

**Additional Context**
I realized there are many occurrences of expression like  `key-${id || ''}` ([getNodeById()](https://github.com/uber/react-digraph/blob/912a8f49e1a8f30e180719f04706622b7d58b10b/src/components/graph-view.js#L309)).
It seems there are similar value checks everywhere in the code, which does special behaviour when id = 0.
I think it is helpful to explicitly state that the key must not be 0 in the doc and/or throw an appropriate error message.

**Comment by ajbogh** [comment]
Thanks for finding this! For context, it was originally intended that IDs would be string-like, such as UUIDs or even database-driven integer IDs. Ideally you would never have a 0-based number. This is the reason why it was programmed with a falsey expression. As you found, this causes an issue with 0-based numbers. 

You can certainly create a PR with a fix, perhaps a trinary `{id != null ? id : ''}` instead. We would also appreciate anyone willing to strengthen the code or make it cleaner.
