### ISSUE TITLE
Graph Controls Positioning

### ISSUE THREAD

**Issue by chandjenAC** [uber/react-digraph#223]
Appreciate all efforts put in developing this awesome library.. I have been using this since the last couple of months and I came across a situation where I need to position the graph controls.

Is there a provision there to modify the position of graph controls ?

Thank you guys !

**Comment by ajbogh** [comment]
The graph controls can be targeted with CSS and moved using absolute positioning. You can override the CSS in your own stylesheet. Use the `.graph-controls` class to move the entire element. You can find the base graph-controls CSS in the main.scss file.

https://github.com/uber/react-digraph/blob/master/src/styles/main.scss#L118

**Comment by chandjenAC** [comment]
Thank you so much for the quick reply... will try to implement it..

**Comment by chandjenAC** [comment]
it worked !!...thanks once again for your time..really appreciate it.
