### ISSUE TITLE
Custom Component Renders for each Type

### ISSUE THREAD

**Issue by EfstathiadisD** [uber/react-digraph#225]
**Is your feature request related to a problem? Please describe.**
I am considering in using this Library, for a Large scale Graph effort. My use-case is kind of complicated though. We need Custom-React-Components, for each Node Type. We have 5 currently, and it is bound to increase.

**Describe the solution you'd like**
I would like to know, if it is currently, supported by the Library, the use of `custom-component`. And if yes, an example `code-sandbox` would be great. To give you an example of what I am talking about:

```javascript
fucntion customRenderComponentForTypeNodeA(data, ...props) {
  <div className="className" {...props}>
     Some Text
     <InnerComponent metrics={data.mertricA}  />
  </div>
} 
```
I have looked a bit around, and found that `render` only accepts SVGs and `renderText` I haven't been able to make it work.

**Additional context**
If you can provide an example on this `codeSandBox` https://codesandbox.io/s/react-digraph-nkvfe?file=/src/config.js ,  it would be amazing. Just add the above example, if a type of Node, that would be enough. Thank you for your work and help..

**Comment by ajbogh** [comment]
The library provides a `renderNode` feature that overrides the default node rendering method. You can provide your own method that returns the component. You're correct, however, that the component should be an SVG, but you can use any SVG features you like, such as foreignObject.

In a project I'm familiar with we use the node type to determine which custom node component to return. We have several node folders, each with their own node config and SVG representations. Our renderNode function analyses the state and selection criteria to produce the correct SVG representation of the node.

**Comment by EfstathiadisD** [comment]
Thanks. I will close the issue for now. That being said, I will re-open it in the future, cause I want to document it with some examples. In general, the Library, seems awesome, but the Docs, are not the best. In any case thank you!!
