### ISSUE TITLE
Issues rendering Edges on Custom Components

### ISSUE THREAD

**Issue by EfstathiadisD** [uber/react-digraph#226]
**Describe the bug**
When using custom components, Edges are not started from the center, but rather from the top-left corner of the component. And I can find no documentation on how to fix it.

**To Reproduce**
To reproduce check out this CodeSandbox. https://codesandbox.io/s/react-digraph-632fb

**Expected Behaviour**
In the following code below, I have used the `renderNode` method, to create a few custom component.
```js
  renderNode = (nodeRef, data, id, selected, hovered, children) => {
    return (
      <svg>
        <g x="0" y="0" className={`shape`}>
          <foreignObject
            style={{ pointerEvents: "all" }}
            width="250"
            height="300"
            xmlnsXlink="http://www.w3.org/1999/xlink"
          >
            <NodeElement data={data} nodeTypes={data.type} id={id} />
          </foreignObject>
        </g>
      </svg>
    );
  };
```
But the node edges are not configured correctly. They should start from the right center and stop on the left center of each component.
**Screenshots**

**Comment by EfstathiadisD** [comment]
On top of that, it would be awesome, if we had some Documentation on simple issues, like that. I understand, this is probably something stupid, I am doing on my code, but the lack of Docs and examples is not helping the situation.

**Comment by ajbogh** [comment]
Your node SVG has no width, height, or viewbox, making it essentially a 0px dot for the edge to connect to. The viewbox is the minimum requirement for react-digraph to guess the dimensions of the node, however it prefers to use the width and height properties if available. The edges use this information to calculate the edge positions around the node shape. 

In order for the edge to wrap itself around the edge of a rectangle, the first element in the SVG must be a rectangle. You don't have to include anything in the rectangle element, simply include a rectangle with the proper height and width proportions.

On another note, typically we use `symbol` as the wrapper element for our shape, not SVG.

See the examples here: https://github.com/uber/react-digraph/blob/master/src/examples/graph-config.js

Here's a suggestion for your element, however you may need to update it slightly.
```
<symbol viewBox="0 0 250 300" width="250" height="300" id="myshape">
  <rect x="0" y="0" width="250" height="300" />
  <g x="0" y="0" className={`shape`}>
      <foreignObject
        style={{ pointerEvents: "all" }}
        width="250"
        height="300"
        xmlnsXlink="http://www.w3.org/1999/xlink"
      >
        <NodeElement data={data} nodeTypes={data.type} id={id} />
      </foreignObject>
  </g>
</symbol>
```

**Comment by EfstathiadisD** [comment]
First of all thanks for your help @ajbogh . I have some good news and bad news. I managed to make my Sandbox work. You can check it out here: https://codesandbox.io/s/react-digraph-vmbet?file=/src/config.js . With that being said, I have to say `renderNode` and `symbol` did not work at all.. To make it work, I had to use `renderNodeText`. **Can you please explain to me why `renderNode` doesn't work. It just didn't print anything to the DOM.**

**Comment by ajbogh** [comment]
It looks to me like you're doing the right thing. The renderNode function in react-digraph uses the config.js file's node type. Your node configuration looks fine there. I made a minor change to include 2px stroke in my version, but you don't seem to need that.

The text rendering also looks fine. You are including foreignObjects, which is fine, and it looks like it's performing adequately.

Remember that both renderNode and renderNodeText are provided so that you can perform customization on the node based on various properties. Perhaps you want to change text, or modify node styles. We use them to customize the icon colors and text when nodes are selected.

If you can get away with your config.js SVG for the node type and use the default functions as much as possible, then that is the best approach.
