### ISSUE TITLE
InitialBBox - Document the feature better

### ISSUE THREAD

**Issue by EfstathiadisD** [uber/react-digraph#235]
**Is your feature request related to a problem? Please describe.**
I want to understand how to use this library. I have the problem of the initial render of the Graph, having a transitioning effect. I solved it with the `initialBBox` thing. The problem, is I don't know how to use it.

**Describe the solution you'd like**
I want to understand what the property is doing. Sure, I passed the object(Below) and it worked, but why did it work? I don't understand. 

```typescript
initialBBox={{ x: 0, y: 0, width: 1000, height: 50 }}
```

> There is also the problem of that solution working only for a relative number of nodes. Which mean, I should pass a function that calculates the total area of the nodes and center them based on that. If I understand correctly.

**Additional context**
I am more than happy to write the docuementation myself, but please can someone explain to me how it's working. So, I can sharre the example in the Docs/ReadMe. Thank you!

**Comment by ajbogh** [comment]
#118 was the PR that landed the initialBBox feature. Please feel free to add more documentation. You may like to include the idea that it disables the zoom-to-fit feature if provided.

Regarding the second point, about passing a function. This can be handled by testing the type of the initialBBox prop and if it's a function then execute it. The external developer will have to determine what this function does, and the response should probably be the same `{x, y, width, height}` object.
