### ISSUE TITLE
Change edge stroke-width dynamically

### ISSUE THREAD

**Issue by Djazouli** [uber/react-digraph#241]
**Is your feature request related to a problem? Please describe.**
I would like to be able to render edges with a different stroke width. For example, in my case, all edges have a specific value, ranging from 0 to 1. I would like to be able to make edges with a value of 0.7 thicker than edges with a value of 0.3. Is it possible ?

**Describe the solution you'd like**
It would be great to have a parameter to do so, or a **renderEdge** function (even if it means copy pasting the one from the source code and adding some arguments).
Also, it would be handy to be able to have a different edgeHandleSize for every node (so that its size fits the size of edge.handleText for example) (renderEdgeHandle function ?)

**Describe alternatives you've considered**
Currently, I am changing the thickness by changing 
`.view-wrapper .edge {
    stroke-width: 4px
}`
in my CSS, but that changes the thickness of all edges.

**Additional context**

**Comment by ajbogh** [comment]
You can use the `afterRenderEdge` function which is called for all edges that are rendered. The structure is this:

    afterRenderEdge?: (id: string, element: any, edge: IEdge, edgeContainer: any, isEdgeSelected: boolean) => void;

You can use this information to check if the edge should be modified based on your requirements and either use the "element" property to directly modify the edge element, or use the edgeContainer to update things within the container.

**Comment by Djazouli** [comment]
Thank you very much, I was able to modify my edge's stroke-width !
