### ISSUE TITLE
create edges on firefox 

### ISSUE THREAD

**Issue by AhmadYoussef** [uber/react-digraph#248]
**Describe the bug**
I am actually facing a problem with firefox ... when I wanna create a new edge between a normal node and complex shape node, it doesn't connect the two nodes from the first try

**To Reproduce**

First of all, you have to get a complex node.
Then press shift and click on any node and try to connect it with complex shape node (for example node G(8) or loop), and  you will find some time that the action createEdge doesn't happen

**Expected behavior**
 it should create an edge from the first try.

**Screenshots**
![Bildschirmfoto 2020-08-05 um 10 55 31](https://user-images.githubusercontent.com/5328749/89500344-e04ca200-d7c1-11ea-9efe-0514c1120b22.png)

**Desktop (please complete the following information):**

**Additional context**
It works perfectly in chrome.
I don't know if I am doing something wrong or perhaps there is a bug here

**Comment by ajbogh** [comment]
I've updated the code in version 7.0.0-alpha.5 so you should have better luck with drawing edges using the latest code.
