### ISSUE TITLE
What is the motivation for `emptyType` 

### ISSUE THREAD

**Issue by mac-s-g** [uber/react-digraph#25]
I'm using a few different nodeTypes.

I can specify one of those as the `emptyType` or 'DefaultType' (from docs).

The node specified as `emptyType` seems to have labels nicely centered in the middle of the node.

all other nodes render labels near the bottom of the component.

I see that logic here: https://github.com/uber/react-digraph/blob/master/src/components/graph-view.js#L698

i'm curious what type of use case you see that offset helpful for.

thank you!

**Comment by johnvf** [comment]
For our use case, users would create nodes and then later attach attributes to them which would change their node type. For nodes which had these attributes attached, we wanted to show an icon in the middle of the node and text below it. For nodes without any attributes, we would simply show the text for the node in the middle.

**Comment by mac-s-g** [comment]
thanks for responding!  makes sense!
