### ISSUE TITLE
Disable Edge or Node Separatly

### ISSUE THREAD

**Issue by Malikx-Alee** [uber/react-digraph#261]
Is their any way to disable the drag behavior of the Edge or Node separately ? Currently if we define graph as read only it disable movement of all items on the graph. @ajbogh

**Comment by ajbogh** [comment]
You can pass a canCreateEdge and canSwapEdge function that returns false when the user can't draw or drag edges. You can also pass your own renderNode function that returns null when it shouldn't render a node. Perhaps you would like to extend the "can" functions to include other things, like "canDragNode", "canCreateNode", "canSelectNode", and "canSelectEdge".

If you're willing to submit a PR, we would appreciate the support.

**Comment by man-person** [comment]
any news with this one?
