### ISSUE TITLE
double-click node handler

### ISSUE THREAD

**Issue by efran50** [uber/react-digraph#3]
Is it possible to add a double-click node handler? It would be useful to update some data on the fly, among other things

**Comment by johnvf** [comment]
Sure, no problem. I can look into this early next week or if you feel like forking it an wading in, feel free to do so and submit a PR.

**Comment by johnvf** [comment]
It looks like you settled this out on your branch. Interested in submitting a pull request for this?

I'm closing this issue out in the meantime.
