### ISSUE TITLE
v8.0.0-beta.2 - can not delete edges

### ISSUE THREAD

**Issue by zanettin** [uber/react-digraph#311]
**Describe the bug**
Using v8.0.0-beta.2 does no longer allow to delete `edges` using `backspace` or `delete` key.

**To Reproduce**
1. have a look at this line in the repo https://github.com/uber/react-digraph/blob/master/src/components/graph-view.js#L598
2. if just `edges` map is defined an no `node` is selected, the `handleDelete` fn won't be executed.

**Expected behavior**
Edges can be deleted w/o an edge selected

**Screenshots**
https://github.com/uber/react-digraph/blob/master/src/components/graph-view.js#L598

**Desktop (please complete the following information):**
 - OS:  `all`
 - Browser `all`
 - Version `*`

**Additional context**
IMO we should remove the selected line and just check for the backspace key to break the switch case 👍 

BTW: THANKS A LOT for providing this lib to all of us! ❤️

**Comment by ajbogh** [comment]
Thank you for pointing that out! We always appreciate the community assisting in the development, so if you're willing to change the line we would be happy to merge the change into the codebase. This gives you the honor of being a bug reporter as well as a contributor.

The team would be happy to fix this if you're not comfortable with the change, just let us know.

**Comment by zanettin** [comment]
@ajbogh sure thing 👍  PR is open and thanks again for your work on this 👍
