### ISSUE TITLE
SelectionT should have edges defined as Map<string, IEdge>, not Map<string, INode>

### ISSUE THREAD

**Issue by SageFioLange** [uber/react-digraph#318]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-digraph@8.0.0-beta.6` for the project I'm working on.

The type definition for SelectionT has edges listed as Map<string, INode> | null, when it should instead be Map<string, IEdge> | null.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-digraph/typings/index.d.ts b/node_modules/react-digraph/typings/index.d.ts
index 6b8a616..172e4ac 100644
--- a/node_modules/react-digraph/typings/index.d.ts
+++ b/node_modules/react-digraph/typings/index.d.ts
@@ -96,7 +96,7 @@ declare module 'react-digraph' {
 
   export type SelectionT = { 
     nodes: Map<string, INode> | null, 
-    edges: Map<string, INode> | null 
+    edges: Map<string, IEdge> | null 
   };
 
   export const Edge: React.Component<IEdgeProps>;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ajbogh** [comment]
The master branch has fixed this issue via #317. I will release the new version shortly (likely 8.0.0 final). Thank you for opening this issue.
