### ISSUE TITLE
Add ability for custom node contents

### ISSUE THREAD

**Issue by imbeyondboredom** [uber/react-digraph#36]
We have a use-case where we'd like to have three text fields that one could edit independently by clicking the node and then editing them in a separate text box. Looking at the readme gif this looked possible but in looking at the code it seems that it's only possible to set a subtype with a hardcoded look and feel.

Example of what we're trying to make: (This is all one node)
```
 --------------- 
|   First line  |   <- Editable text
|--------------
|   Second line |   <- Editable text
|-------------- 
|   Third line  |   <- Editable text
 ---------------
```

If this is possible now - how could we accomplish this?
If not - is this something you're interested in adding?

**Comment by johnvf** [comment]
I can think of a few ways/some combination of:
- Define the interaction for renaming nodes on the subtypes which you pass in (EG - make editable fields and attach click handlers etc..)
- Override the 'renderNode' function with whatever custom logic you wish
- Open external modals or other parts of the UI in the 'onSelectNode' handler of your parent component

**Comment by dbvrac** [comment]
I'd love to get some examples, or if you wouldn't mind expanding on your answer that would be great. I have a need for a wide variety of styling and functionality for both nodes and edges as part of a larger React app.
Much thanks.

**Comment by ajbogh** [comment]
Just to follow up on this, the renderNode function can be utilized to render your own custom nodes. There's also a renderNodeText option which is called in place of react-digraph rendering the text itself. You can override both of these, or not use renderNodeText and instead render all of your text and nodes within the renderNode function. The functions will receive parameters that you can use with d3 to select or build custom components.

If you would like more examples, please create a new issue asking for improved examples (so we don't mistake the title), or help us by documenting your own examples. We would appreciate all the help we can get!
