### ISSUE TITLE
Can't set up

### ISSUE THREAD

**Issue by TomReidNZ** [uber/react-digraph#37]
I cloned the repo and installed. This is the error I get:

'rm' is not recognized as an internal or external command,
operable program or batch file.

my npm version is 5.7.1

**Comment by johnvf** [comment]
Hi Tom - this sounds like an issue with your environment or setup, not the library. 

The startup scripts assume you're using a Bourne shell - you may have to fork it and modify them to support a different terminal that doesn't have an 'rm' command.
