### ISSUE TITLE
when readOnly prop changes, the state doesn't change

### ISSUE THREAD

**Issue by chiwoojo** [uber/react-digraph#43]
We were having a issue where when the readOnly prop changes, the state does not change, so you cannot create nodes.

It was here before:
https://github.com/uber/react-digraph/blob/540a1ef5977344b28af93b139fad1f539b0bd954/src/components/graph-view.js#L218

but was taken out in the recent refactor?

**Comment by ajbogh** [comment]
I believe this is fixed in recent builds. Please check with the latest 4.x release. Feel free to reopen this issue if it's not fixed.
