### ISSUE TITLE
Firefox support for event and d3.event 

### ISSUE THREAD

**Issue by nishantrpai** [uber/react-digraph#45]
When you try to click on any node in firefox you face this error on the console where it says `ReferenceError: event is not defined` and none of the creation nodes, create edge etc works. Surprisingly delete works fine. So I decided to see if there any solution and lo and behold 
https://stackoverflow.com/questions/48227127/d3-event-showing-referenceerror-event-is-not-defined-in-firefox

I request the authors to change it from event.target to d3.event.target.

**Comment by nishantrpai** [comment]
I think we hacked our way around by used `d3.event` instead of `event`, but I am not sure if that's the way to go.

**Comment by ajbogh** [comment]
I believe this is fixed in recent builds. Closing for now, but please feel free to reopen if you still notice an issue with the 4.x builds.

**Comment by iamsoorena** [comment]
@ajbogh It's not fixed in latest` v4.x.x` release, But it will be If you merge [this](https://github.com/uber/react-digraph/pull/82)
