### ISSUE TITLE
Can't run build

### ISSUE THREAD

**Issue by maulberto3** [uber/react-digraph#48]
After `npm i`, can't run script `"build": "rm -rf dist && babel src -d dist --copy-files -s"`, as there is no way npm recognizes `rm`. Any help?

**Comment by Prior99** [comment]
I guess you are running on Windows. Try executing the from a cygwin, mingw or git shell.

**Comment by maulberto3** [comment]
Yes, I am on Windows. Will try your syggestion soon.
