### ISSUE TITLE
Shape Component vs Shape SVG

### ISSUE THREAD

**Issue by JosephMart** [uber/react-digraph#49]
Really nice work! Very pretty project. I was wondering if it is possible out of the box to have a node shape to be a React component in the sense that it is still rendering a SVG shape but the props (name etc...) is being passed into the shape.

Thanks!

**Comment by JosephMart** [comment]
After looking into the source code, would this be possible with a custom `renderDefs` function? Thanks

**Comment by JosephMart** [comment]
The way I worked around this was still defining different svg elements for different nodes but the dynamic data was not linked in any way to the svg directly. The dynamic data was superimposed over top the element with the `renderNode` function

**Comment by shreyasparbat** [comment]
Hi @JosephMart, would you mind sharing an example of how you were able to achieve the above? Thank you!
