### ISSUE TITLE
Move radium/react-icons/d3 peerDependencies to dependencies

### ISSUE THREAD

**Issue by NameFILIP** [uber/react-digraph#58]
It's unclear why they are `peerDependencies` instead of direct `dependencies`. In our case, we don't really need neither `radium` nor `react-icons`. Why should I add it to the project as a dependency? A related PR: https://github.com/uber/react-digraph/pull/47

**Comment by ajbogh** [comment]
Uber legal has concerns regarding including third party code in the distribution files. The original intent was to make the distribution as small and legally clean as possible, without requiring extra licenses. 

With that said, I agree that radium and react-icons are direct dependencies to the project so they make sense to include in the distribution. In the future we will be removing radium and including the react-icons in the dependencies. See the v5-alpha branch for more info.

**Comment by ajbogh** [comment]
@NameFILIP it looks like #47 needs a rebase and CLA signed. I've asked the developer to do so, and I hope that we can close that PR soon. If you've signed the CLA and would like to make your own PR, please feel free.

**Comment by ajbogh** [comment]
Just to follow up on this, I'm also making the change within the new react-digraph codebase. You can find it in the v5-alpha branch.

**Comment by vicapow** [comment]
you can use individual d3 packages instead of the top level package. https://www.npmjs.com/search?q=d3-

**Comment by ajbogh** [comment]
Thanks @vicapow. We will have to do that at a later date, unless you would be willing to submit a new PR. I'd be happy to review it and work with you on it.

**Comment by NameFILIP** [comment]
The publish size has increased just a little bit. The big spike is in the install size, because install now downloads what used to be peer dependencies. But for a user of the library this doesn't change anything, because either as a dependency or as a peer dependency it will take the same amount of space in the node_modules.
