### ISSUE TITLE
Uncaught TypeError: nodesSelection.exit(...).transition is not a function

### ISSUE THREAD

**Issue by NameFILIP** [uber/react-digraph#71]
We're getting this error on v4.1.5:
```
graph-view.js:693 Uncaught TypeError: nodesSelection.exit(...).transition is not a function
    at RadiumEnhancer.GraphView._this.renderNodes (graph-view.js:693)
    at RadiumEnhancer.GraphView._this.renderView (graph-view.js:790)
    at RadiumEnhancer.render (graph-view.js:929)
    at RadiumEnhancer.render (enhancer.js:265)
    at finishClassComponent (react-dom.development.js:13085)
    at updateClassComponent (react-dom.development.js:13047)
    at beginWork (react-dom.development.js:13715)
    at performUnitOfWork (react-dom.development.js:15741)
    at workLoop (react-dom.development.js:15780)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
```

This does not happen on this commit of the fork: https://github.com/vicapow/react-digraph/tree/d3-as-direct-dependency-dist

**Comment by ajbogh** [comment]
Thanks @NameFILIP. I'll take a look at this and get a fix in likely tomorrow with a patch bump.

**Comment by ajbogh** [comment]
@NameFILIP, I couldn't repro the problem using the latest master branch with a slight fix for zooming using d3 v4.13.0 (upgraded). You can see my code changes in #72. Perhaps you can check out the PR and test it to make sure it solves your issue.

**Comment by estiller** [comment]
Hey @ajbogh, I started writing a simple app using this component and I ran into the exact same issue that @NameFILIP mentioned above. I started investigating and found something very interesting - if I clone this repository "as-is", build it with `yarn install` and then try and run the [example](https://github.com/uber/react-digraph/blob/master/src/examples/graph.js) with `yarn run example` or `npm run example` - it reproduces the issue! However, what is weirder than that is that if I take this exact same repo and install dependencies with `npm install` then the same example works!

Moreover, if now I go to **my own app** (which has it's dependencies installed with `yarn install`) and run `npm install` instead - then my app starts working... Can you think of any reason for this behavior? Which packages are resolved differently?

**Comment by NameFILIP** [comment]
Great find @estiller, my app uses `yarn`.

**Comment by NameFILIP** [comment]
Upgraded to v4.1.6 and the issue does not happen anymore.

**Comment by ajbogh** [comment]
@NameFILIP Thanks for testing out v4.1.6. I've fixed this issue with yarn by upgrading d3 to v5. For some reason yarn didn't work correctly with v4.13.0. I'm hoping that upgrading to v5 doesn't negatively impact anyone.
