### ISSUE TITLE
Can't delete selected edge

### ISSUE THREAD

**Issue by philippov** [uber/react-digraph#93]
I suppose handleDocumentClick fires when an edge is selected. So state.focused becomes false and delete doesn't work.

**Comment by ajbogh** [comment]
Hi @philippov. Is this happening with the latest react-digraph? I haven't seen any issues recently other than for edges that have the same target node as the parent (#101).

**Comment by pash90** [comment]
@ajbogh Any updates on this issue? I'm facing the same thing. Can't delete the selected edge.

**Comment by pash90** [comment]
@ajbogh @philippov This is the error I get. 
![image](https://user-images.githubusercontent.com/24995648/53371012-4ca75d00-39a3-11e9-9172-51124117ad69.png)

![image](https://user-images.githubusercontent.com/24995648/53371050-621c8700-39a3-11e9-846f-0af8b7fc505e.png)

Also to note, if I remove the `onDeleteEdge` custom handler that I am providing to `GraphView`, the error disappears and it starts working properly.

**Comment by ajbogh** [comment]
@pash90 I'm doing project cleanup duty this week, so I'll be checking out, commenting on, and closing a number of PRs. I sincerely hope to close this PR soon.

**Comment by pash90** [comment]
@ajbogh Much much appreciated brother!
