### ISSUE TITLE
Add edge labels in v5

### ISSUE THREAD

**Issue by iamsoorena** [uber/react-digraph#95]
**Is your feature request related to a problem? Please describe.**
I want to add edge labels in version 5
like this:
![image](https://user-images.githubusercontent.com/15319886/49685398-efb0af00-faf7-11e8-9f83-667898984baf.png)

**Describe the solution you'd like**
I think It will be helpful to have `renderEdge` back.

**Describe alternatives you've considered**
I think we can have a separate `renderEdgeLabel` function for this.

**Comment by tony-garcia** [comment]
How can the edge label be rendered like that? Along the edge?
